### ISSUE TITLE
Hide/minimise "sign in" area

### ISSUE THREAD

**Issue by gingerbeardman** [timche/gmail-desktop#200]
Please allow hiding or minimising of this "sign in" area:

![Screen shot 2020-07-22 at 11 38 00](https://user-images.githubusercontent.com/49612/88166821-cd599f80-cc0f-11ea-90d2-1e04fe9c735a.png)

**Comment by gingerbeardman** [comment]
I did this using custom style

```css
div[aria-label=Hangouts] { 
   display: none;
}

div[role=navigation] { 
   height: auto !important;
}
```
